// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HW_EFCoreWebAPI.Models
{
    public partial class VwCourseStudents
    {
        [Column("DepartmentID")]
        public int? DepartmentId { get; set; }
        [StringLength(50)]
        public string DepartmentName { get; set; }
        [Column("CourseID")]
        public int CourseId { get; set; }
        [StringLength(50)]
        public string CourseTitle { get; set; }
        [Column("StudentID")]
        public int? StudentId { get; set; }
        [StringLength(101)]
        public string StudentName { get; set; }
    }
}