// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
/** Class-1214: 實作 PATCH API 更新一個實體的部分資料 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HW_EFCoreWebAPI.Models
{
    public partial class Course_
    {
        [StringLength(50)]
        public string Title { get; set; }
        public int Credits { get; set; }
        public bool IsDeleted { get; set; }
    }
}