// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace EFCoreTest.Models
{
    public partial class CourseInstructor
    {
        [Column("CourseID")]
        public int CourseId { get; set; }
        [Column("InstructorID")]
        public int InstructorId { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("CourseInstructor")]
        [JsonIgnore] // Class-1208: 將導覽屬性放入一起回傳
        public virtual Course Course { get; set; }
        [ForeignKey("InstructorId")]
        [InverseProperty("CourseInstructor")]
        public virtual Person Instructor { get; set; }
    }
}